### ISSUE TITLE
Fix block drop doubling when using skyroot tools

### ISSUE THREAD

**Issue by ColinSweetland** [bta-team-port/better-with-aether#166]
Currently this is completely broken (happens with all tools) and the code for what makes it happens is very spread around.

Theres a BlockMixin that's supposed to make this happen, but I don't think it does anything and can be completely removed safely

There's a class 'BlockAetherDouble' which blocks that extend should drop double, but it doesn't properly check for skyroot material.

Also many blocks which should extend 'BlockAetherDouble' instead have the same logic copy/pasted into there class (e.g. quicksoil)

I think the best way to fix this is to give blocks which should have doubled drops a BlockTag, and check for that block tag in a mixin to Block.onBlockDestroyedByPlayer (to double the drops) and ItemBlock.onItemUse (to give player placed blocks a different metadata)

**Comment by UselessBullets** [comment]
Issue has been resolves, though suggested implementation is still probably a cleaner way of getting the functionality
