### ISSUE TITLE
Boss chests are not opened by keys

### ISSUE THREAD

**Issue by Crobii** [bta-team-port/better-with-aether#232]
While player placed chests work fine, the naturally generated boss chests refuse to open, regardless of key

**Comment by Olypolyu** [comment]
you're probably using the wrong key as they are bound to the boss itself.

**Comment by Olypolyu** [comment]
can you provide a video of the behavior?

**Comment by FatherCheese** [comment]
Doesn't seem to be happening on my end (1.7.7.1) so I'll close this for now. Feel free to reopen later if it happens again.
